define({
        _featureAction_LRSLocatorPoint: "Use point in LRS Locator",
        in: "en ",
        identifyLabel: "Identificar",
        attributeSetLabel: "Conjunto de atributos de consulta",
        resultsLabel: "Resultados",
        clearButtonText: "Despejado",
        exportButtonText: "Exportar a",
        fromMeasureText: "De medida:",
        intersectionPickerText: "Capa de intersección:",
        invalidRouteId: "ID de ruta no válida: ",
        locateButtonText: "Localizar",
        measureText: "Punto de milla:",
        fromMeasureText: "de la medida",
        toMeasureText: "para medir",
        networkLayerText: "Capa de red:",
        routeIdText: "ID de ruta:",
        routeNameText: "Nombre de ruta:",
        attributeSetText: "conjunto de atributos:",
        selectAllButtonText: "Identificar puntos de milla",
        selectMeasureTooltip: "Seleccionar una medida de una ruta",
        byRoute: "por Ruta",
        byPoint: "por Punto",
        byFile: "por CSV",
        importCsv: "Importar CSV",
        invalidMeasure: "Please enter a valid measure.",
        measurePrecision: "Medir la Precisión:",
        searchTolerance: "Search Tolerance:",
        selectAllButtonTooltip: "Identifique puntos de milla para todas las rutas en la ubicación en el mapa",
        selectAllDrawTooltip: "Haga clic en la ruta para mostrar atributos",
        selectRouteDrawTooltip: "Haga clic para seleccionar una ruta en ",
        areYouSure: "¿Está seguro de que le gustaría borrar los resultados?",
        dontAskAgain: "No vuelvas a preguntar",
        noRouteFound: "No se encontró ninguna ruta. Seleccione una ruta en ",
        clearResults: "Eliminar resultados",
        exportResults: "Exportar resultados",
        selectPointDrawTooltip: "Haga clic en el mapa para agregar un punto",
        invalidCoords: "Ingrese coordenadas válidas",
        selectRouteBtnTooltip: "Selecciona una ruta en el mapa",
        toMeasureText: "Para medir (opcional):",
        loadingText: "Esperando al servidor...",
        lodAlert1: "Actualmente, el mapa no se ha ampliado lo suficiente como para realizar una búsqueda precisa.",
        lodAlert2: "Por favor amplíe al menos | nivel(es).",
        lodAlertTitle: "Alerta de consulta",
        intersectionLabel: "Ajustar a la intersección más cercana",
        intersectionTooltip: "Al realizar una acción de clic en el mapa, el punto resultante se ajustará al punto de intersección más cercano. Una indicación visual mostrará cuando esto sea posible.",
        addToLabel: "Agregar nuevas búsquedas a los resultados actuales",
        precisionTooltip: "La precisión de la medida da como resultado lugares decimales",
        attributeSetDescribe: "Ver atributos incluidos",
        changePrecision: "Cambiar la precisión de la medida (lugares decimales)",
        attributeSetTooltip: "Si se marca, se recuperará un conjunto adicional de atributos.",
        addToTooltip: "Si se marca, los resultados de la búsqueda no se borrarán antes de una nueva búsqueda y los nuevos resultados se agregarán a los resultados anteriores.",
        resultCounter: "Resultados encontrados: ",
        resultTooltip1: "Al hacer clic en 'Resaltar resultado' se resaltará el resultado. Para las líneas segmentadas, aparecerá una flecha para mostrar qué medidas de dirección aumentan.",
        resultTooltip2: "Al hacer clic una vez en un resultado, se desplazará al resultado, mientras que al hacer doble clic se ampliará el resultado.",
        measureBoxProps: "constraints:{min:0,max:5000,places:7}, invalidMessage:'Por favor ingrese un valor numérico positivo.', rangeMessage:'Punto de milla no válido.'",
        filenameBoxProps: "regExp: '[a-zA-Z0-9_ ]+', invalidMessage:'Nombre de archivo inválido.'",
        dropFile : "Suelte el archivo aquí",
        or: "O",
        browseFiles: "Búsqueda de archivos",
        latitude: "Latitud (Y)",
        longitude: "Longitud (X)",
        esriUnknownUnits: "Unknown Units",
        points: "Points",
        esriPoints: "Points",
        inches: "Inches",
        esriInches: "Inches",
        feet: "Feet",
        esriFeet: "Feet",
        yards: "Yards",
        esriYards: "Yards",
        miles: "Miles",
        esriMiles: "Miles",
        nauticalMiles: "Nautical Miles",
        esriNauticalMiles: "Nautical Miles",
        millimeters: "Millimeters",
        esriMillimeters: "Millimeters",
        centimeters: "Centimeters",
        esriCentimeters: "Centimeters",
        decimeters: "Decimeters",
        esriDecimeters: "Decimeters",
        meters: "Meters",
        esriMeters: "Meters",
        kilometers: "Kilometers",
        esriKilometers: "Kilometers",
        decimalDegrees: "Decimal Degrees",
        esriDecimalDegrees: "Decimal Degrees"
});
