define({
        _featureAction_FindMilepoint: "Encuentra puntos de milla",
        identifyLabel: "Identificar",
        resultsLabel: "Resultados",
        clearButtonText: "Despejado",
        exportButtonText: "Exportar a",
        fromMeasureText: "De medida:",
        invalidRouteId: "ID de ruta no válida: ",
        locateButtonText: "Localizar",
        measureText: "Punto de milla:",
        networkLayerText: "Capa de red:",
        routeIdText: "ID de ruta:",
        routeNameText: "Nombre de ruta:",
        selectAllButtonText: "Identificar puntos de milla",
        selectAllButtonTooltip: "Identifique puntos de milla para todas las rutas en la ubicación en el mapa",
        selectAllDrawTooltip: "Haga clic en la ruta para mostrar atributos",
        selectRouteDrawTooltip: "Haga clic para seleccionar una ruta",
        selectRouteBtnTooltip: "Selecciona una ruta en el mapa",
        toMeasureText: "Para medir (opcional):",
        lodAlert1: "Actualmente, el mapa no se ha ampliado lo suficiente como para realizar una búsqueda precisa.",
        lodAlert2: "Por favor amplíe al menos | nivel(es).",
        lodAlertTitle: "Alerta de consulta",
        intersectionLabel: "Ajustar a la intersección más cercana",
        intersectionTooltip: "Las búsquedas devolverán automáticamente los datos de la intersección más cercana dentro del radio de búsqueda dado.",
        addToLabel: "Agregar nuevas búsquedas a los resultados actuales",
        addToTooltip: "Si se marca, los resultados de la búsqueda no se borrarán antes de una nueva búsqueda y los nuevos resultados se agregarán a los resultados anteriores.",
        resultCounter: "Resultados encontrados: ",
        resultTooltip1: "Consejo: Al hacer clic en 'Resaltar ruta', se mostrará la ruta del resultado junto con flechas que apuntarán en la dirección en que aumentan los puntos de millas.",
        resultTooltip2: "Al hacer clic una vez en un resultado, se desplazará al resultado, mientras que al hacer doble clic se ampliará el resultado.",
        measureBoxProps: "constraints:{min:0,max:5000,places:7}, invalidMessage:'Por favor ingrese un valor numérico positivo.', rangeMessage:'Punto de milla no válido.'",
        filenameBoxProps: "regExp:'[a-zA-Z0-9]*', invalidMessage:'Nombre de archivo inválido.'"
});
