define({
  root: ({
    addNetworkLayer: "Add a Network Layer",
    actions: "Actions",
    layerTitle: "Network Layer",
    serviceURL: "Service URL",
    warning: "Incorrect input",
    urlNotAvailable: "The url is not available",
    notPrintTask: "The url is not a print task",
    advancedOption: "Show advanced options",
    lrsservicewarning: "A valid LRS map service is required.",
    lrslayerwarning: "LRS service has no network layers.",
    lrsenablewarning: "At least one layer must be enabled.",
    intersectionlayerwarning: "The provided intersection layer is not valid.",
    ok: "OK",
    editable: "Editable", 
    updateSearch: "Update Network Layer",
    cancel: "Cancel",//start of added
    invalidsearchlayer: "Invalid Network Layer. Must be of type: esriLRSNetworkLayer",
    searchUrl: "Search URL",
    title: "Title",
    availableFields: "Available Fields",
    name: "Name",
    alias: "Alias",
    includedFields: "Included Fields",
    ok: "OK",
    addSearch2: "Add Search",
    includeall: "Include All",
    include: "Include",
    none: "None",
    string: "String",
    number: "Number",
    date: "Date",
    error: {
      invalidParams: "Invalid parameters.",
      invalidUrl: "Invalid URL.",
    },
    edit: "Edit field format",
    dateformat: "Date format",
    friendlyDatePattern: "MM/dd/yyyy",
    dayShortMonthYear: "Day short Month Year",
    longDate: "Long Date",
    longMonthDayYear: "Long Month Day Year",
    longMonthYear: "Long Month Year",
    shortDate: "Short Date",
    shortDateLongTime: "Short Day Long Time",
    shortDateLongTime24: "Short Day Long Time 24",
    shortDateShortTime: "Short Date Short Time",
    shortDateShortTime24: "Short Day Short Time 24",
    shortMonthYear: "Short Month Year",
    year: "Year",
    currencyfield: "Currency Field",
    currencySymbol: "Currency Symbol",
    examplecurrency: "$",
    precision: "Precision",
    exampleprecision: ".",
    usethousandssep: "Use thousands separator",
    examplethousands: ",",
    enable: "Enable",
    hideinpopup: "Hide in Popup"

})
})