define({
  root: ({
    generalNode: "General",
    networkNode: "Network Layers",
    intersectionNode: "Intersection Layers",
    attributeNode: "Attribute Set",
    temporalityNode: "Temporality",
    symbologyNode: "Symbology",
    addNetworkLayer: "Add a Network Layer",
    actions: "Actions",
    addTimeConfig: "Add Date",
    dateTitle: "Date",
    layerTitle: "Network Layer",
    eventTitle: "Event Layer",
    attributeTitle: "Attribute Set",
    addAttribute: "Add Attribute Set",
    editAttribute: "Edit Attribute Set",
    pointTitle: "Point Symbol",
    lineTitle: "Line Symbol",
    includeNetwork: "Include network and route info",
    includeDate: "Include view date",
    intersectionLayerTitle: "Intersection Layer",
    serviceURL: "Service URL",
    allNetworkValid: "All network layers are valid.",
    allIntersectionValid: "All intersection layers are valid.",
    allEventValid: "All event layers are valid.",
    temporalityNetwork: "1 or more network layers has a temporal view date.",
    temporalityIntersection: "1 or more intersection layers has a temporal view date.",
    temporalityEvent: "1 or more event layers has a temporal view date.",
    noNetworks: "There are no valid network layers in this map service.",
    noIntersections: "There are no valid intersection layers in this map service.",
    noEvents: "There are no valid event layers in this map service.",
    lastUpdated: "Last updated on ",
    lrsservicewarning: "A valid LRS map service is required.",
    lrslayerwarning: "LRS service has no network layers.",
    lrsenablewarning: "At least one layer must be enabled.",
    timestampwarning: "At least one date must be enabled.",
    intersectionlayerwarning: "There are no intersection layers registered in this service!",
    eventConfig: "Configure Attribute Set",
    intersectionConfig: "Configure Intersection Layers",
    temporalityConfig: "Configure Temporality Settings",
    symbologyConfig: "Configure Symbology Settings",
    ok: "OK",
    editable: "Editable", 
    updateSearch: "Update Network Layer",
    cancel: "Cancel",
    invalidsearchlayer: "Invalid Network Layer. Must be of type: esriLRSNetworkLayer",
    searchUrl: "Layer URL",
    title: "Title",
    availableFields: "Available Fields",
    name: "Name",
    alias: "Alias",
    layer: "Layer",
    includedFields: "Included Fields",
    ok: "OK",
    addSearch2: "Add Search",
    includeall: "Include All",
    include: "Include",
    none: "None",
    string: "String",
    number: "Number",
    date: "Date",
    isempty: "is empty",
    requiredfield: "is required",
    error: {
      invalidParams: "Invalid parameters.",
      invalidUrl: "Invalid URL.",
    },
    edit: "Edit field format",
    dateformat: "Date format",
    friendlyDatePattern: "MM/dd/yyyy",
    dayShortMonthYear: "Day Short Month Year",
    dayShortMonthYearLongTime: "Day Short Month Year Long Time",
    dayShortMonthYearLongTime24: "Day Short Month Year Long Time 24",
    dayShortMonthYearShortTime: "Day Short Month Year Short Time",
    dayShortMonthYearShortTime24: "Day Short Month Year Short Time 24",
    longDate: "Long Date",
    longDateLongTime: "Long Date Long Time",
    longDateLongTime24: "Long Date Long Time 24",
    longDateShortTime: "Long Date Short Time",
    longDateShortTime24: "Long Date Short Time 24",
    longMonthDayYear: "Long Month Day Year",
    longMonthDayYearLongTime: "Long Month Day Year Long Time",
    longMonthDayYearLongTime24: "Long Month Day Year Long Time 24",
    longMonthDayYearShortTime: "Long Month Day Year Short Time",
    longMonthDayYearShortTime24: "Long Month Day Year Short Time 24",
    longMonthYear: "Long Month Year",
    shortDate: "Short Date",
    shortDateLE: "Short Date LE",
    shortDateLELongTime: "Short Date LE Long Time",
    shortDateLELongTime24: "Short Date LE Long Time 24",
    shortDateLEShortTime: "Short Date LE Short Time",
    shortDateLEShortTime24: "Short Date LE Short Time 24",
    shortDateLongTime: "Short Date Long Time",
    shortDateLongTime24: "Short Date Long Time 24",
    shortDateShortTime: "Short Date Short Time",
    shortDateShortTime24: "Short Day Short Time 24",
    shortMonthYear: "Short Month Year",
    year: "Year",
    timestamp: "Add Date",
    currencyfield: "Currency Field",
    currencySymbol: "Currency Symbol",
    examplecurrency: "$",
    precision: "Precision",
    exampleprecision: ".",
    usethousandssep: "Use thousands separator",
    examplethousands: ",",
    enable: "Enable",
    hideinpopup: "Hide in Popup"

})
})