define({
    root:({
        _featureAction_FindMilepoint: "Find Milepoints",
        identifyLabel: "Identify",
        resultsLabel: "Results",
        clearButtonText: "Clear",
        exportButtonText: "Export to",
        fromMeasureText: "From Measure:",
        invalidRouteId: "Invalid Route ID: ",
        locateButtonText: "Locate",
        measureText: "Milepoint:",
        networkLayerText: "Network Layer:",
        routeIdText: "Route ID:",
        routeNameText: "Route Name:",
        selectAllButtonText: "Identify Mile Points",
        selectAllButtonTooltip: "Identify mile points for all routes at location on map",
        selectAllDrawTooltip: "Click route to show attributes",
        selectRouteDrawTooltip: "Click to select a route",
        selectRouteBtnTooltip: "Select a route on the map",
        toMeasureText: "To Measure (optional):",
        lodAlert1: "The map is currently not zoomed in enough to make an accurate search.",
        lodAlert2: "Please zoom in at least | level(s).",
        lodAlertTitle: "Query Alert",
        intersectionLabel: "Snap to nearest intersection",
        intersectionTooltip: "Searches will automatically return data for the closest intersection within the given search radius.",
        addToLabel: "Add new searches to current results",
        addToTooltip: "If checked, search results will not be cleared before a new search and new results will be appended to old results.",
        resultCounter: "Results found: ",
        resultTooltip1: "Tip: Clicking 'Highlight Route' will show the route of the result along with arrows that will point in the direction that mile points increases.",
        resultTooltip2: "Clicking a result once will pan to the result, while double-clicking will zoom to the result.",
        measureBoxProps: "constraints:{min:0,max:Infinity,places:7}, invalidMessage:'Please enter a positive numeric value up to seven decimal places.', rangeMessage:'Invalid mile point.', ",
        filenameBoxProps: "regExp:'[a-zA-Z0-9]*', invalidMessage:'Invalid filename.'"
    }),
    "es": 1
});
