define({
    root:({
        _featureAction_LRSLocatorPoint: "Use point in LRS Locator",
        in: "in ",
        attributeSetLabel: "Query additional attribute set",
        identifyLabel: "Identify",
        resultsLabel: "Results",
        clearButtonText: "Clear",
        exportButtonText: "Export to",
        fromMeasureText: "From Measure:",
        intersectionPickerText: "Intersection Layer:",
        invalidRouteId: "Invalid Route ID: ",
        invalidMeasure: "The measure is invalid. Please enter a valid number.",
        useRouteEnd: "Use the route end",
        useRouteStart: "Use the route start",
        useRouteStartEndGeometryError: "Please enter a valid route with a geometry.",
        useRouteStartEndRouteError: "Please enter a valid route.",
        measureNotLocated: "The measure could not be located on the selected route.",
        attributeSetText: "Attribute Set:",
        locateButtonText: "Locate",
        networkLayerText: "Network Layer:",
        routeIdText: "Route ID:",
        routeNameText: "Route Name:",
        timePickerText: "View Date:",
        byRoute: "by Route",
        byPoint: "by Point",
        byFile: "by CSV",
        importCsv: "Import CSV",
        invalidMeasure: "Please enter a valid route and measure.",
        measurePrecision: "Measure Precision:",
        searchTolerance: "Search Tolerance:",
        selectMeasureTooltip: "Select a measure from a route",
        selectAllButtonText: "Identify Mile Points",
        selectAllButtonTooltip: "Identify mile points for all routes at location on map",
        selectAllDrawTooltip: "Click route to show attributes",
        selectRouteDrawTooltip: "Click to select a route in ",
        selectRouteBtnTooltip: "Select a route on the map",
        areYouSure: "Are you sure you would like to clear results?",
        dontAskAgain: "Don't ask again",
        noRouteFound: "No route found. Please select a route in ",
        invalidCoords: "Please enter valid coordinates.",
        clearResults: "Clear Results",
        exportResults: "Export Results",
        selectPointDrawTooltip: "Click on map to add point",
        toMeasureText: "To Measure (optional):",
        loadingText: "Waiting for server...",
        lodAlert1: "The map is currently not zoomed in enough to make an accurate search.",
        lodAlert2: "Please zoom in at least | level(s).",
        lodAlertTitle: "Query Alert",
        intersectionLabel: "Snap to nearest intersection",
        intersectionTooltip: "When performing a map click action, the resulting point will snap to the nearest intersection point. A visual indicator will show when this is possible.",
        addToLabel: "Add new searches to current results",
        addToTooltip: "If checked, search results will not be cleared before a new search and new results will be appended to old results.",
        attributeSetTooltip: "If checked, an additional set of attributes will be retrieved.",
        precisionTooltip: "The precision of measure results in decimal places",
        attributeSetDescribe: "View included attributes",
        changePrecision: "Change precision of measure (decimal places)",
        resultCounter: "Results found: ",
        resultTooltip1: "Clicking 'Highlight Result' will highlight the result. For segmented lines, an arrow will appear to show which direction measures increase.",
        resultTooltip2: "Clicking a result once will pan to the result, while double-clicking will zoom to the result.",
        measureBoxProps: "constraints:{min:0,max:Infinity,places:7}, invalidMessage:'Please enter a positive numeric value up to seven decimal places.', rangeMessage:'Invalid mile point.', ",
        filenameBoxProps: "regExp: '[a-zA-Z0-9_ ]+', invalidMessage:'Invalid filename.'",
        dropFile: "Drop File Here",
        or: "OR",
        browseFiles: "Browse Files",
        latitude: "Latitude (Y)",
        longitude: "Longitude (X)",
        esriUnknownUnits: "Unknown Units",
        points: "Points",
        esriPoints: "Points",
        inches: "Inches",
        esriInches: "Inches",
        feet: "Feet",
        esriFeet: "Feet",
        yards: "Yards",
        esriYards: "Yards",
        miles: "Miles",
        esriMiles: "Miles",
        nauticalMiles: "Nautical Miles",
        esriNauticalMiles: "Nautical Miles",
        millimeters: "Millimeters",
        esriMillimeters: "Millimeters",
        centimeters: "Centimeters",
        esriCentimeters: "Centimeters",
        decimeters: "Decimeters",
        esriDecimeters: "Decimeters",
        meters: "Meters",
        esriMeters: "Meters",
        kilometers: "Kilometers",
        esriKilometers: "Kilometers",
        decimalDegrees: "Decimal Degrees",
        esriDecimalDegrees: "Decimal Degrees"
    }),
    "es": 1
});
